### ISSUE TITLE
MOTHERLOAD

### ISSUE THREAD

**Issue by todrobbins** [junosuarez/dinosaurs#1]
I'm planning on adding to the base data with this: https://en.wikipedia.org/wiki/List_of_dinosaur_genera

:joy:

**Comment by jden** [comment]
YES DO IT!

**Comment by jden** [comment]
(This is a great example of [Cunningham's Law](http://meta.wikimedia.org/wiki/Cunningham%27s_Law))

**Comment by todrobbins** [comment]
Ha! Totally.

**Comment by js-n** [comment]
hey there, going through cleaning up old issues on repos I maintain. I'd still be more than happy to review and merge a PR for this issue!

**Comment by todrobbins** [comment]
@js-n let me look at where I got on this. It's been a while 😝

**Comment by RatJuggler** [comment]
Hi, love using this list for test data so I've updated it from Wikipedia as suggested and submitted a pull request.

**Comment by junosuarez** [comment]
fixed in #5
